---
minimum_pre_commit_version: 2.9.2
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-merge-conflict  # Check for files that contain merge conflict strings.
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: mixed-line-ending     # Replaces or checks mixed line ending.
        args: [--fix=lf]
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
        args: [--remove]
      - id: check-yaml
      - id: debug-statements
        language_version: python3

  # ----- Local Hooks ----------------------------------------------------------------------------------------------->
  - repo: local
    hooks:
      - id: sort-pylint-spelling-words
        name: Sort PyLint Spelling Words File
        entry: python .pre-commit-hooks/sort-pylint-spelling-words.py
        language: system
        files: ^\.pylint-spelling-words$

      - id: check-changelog-entries
        name: Check Changelog Entries
        entry: python .pre-commit-hooks/check-changelog-entries.py
        language: system

  # <---- Local Hooks ------------------------------------------------------------------------------------------------

  # ----- Formatting ------------------------------------------------------------------------------------------------>
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
      - id: reorder-python-imports
        args:
          - --py39-plus
          - --application-directories=.:src
          - --add-import=from __future__ import annotations
        exclude: src/mcookbook/version.py

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
      - id: pyupgrade
        name: Rewrite Code to be Py3.9+
        args:
          - --py39-plus
        files: ^((setup|noxfile)|(src|tests)/.*)\.py$
        exclude: ^src/mcookbook/(version|(types|config)/.*)\.py$

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
      - id: pyupgrade
        name: Rewrite Custom Types to be Py3.9+
        args:
          - --py39-plus
          - --keep-runtime-typing
        files: ^src/mcookbook/(types|config)/.*\.py$

  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
        args: [-l 100]
        exclude: src/mcookbook/version.py

  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.0
    hooks:
      - id: blacken-docs
#        args: [--skip-errors]
        files: ^((docs/.*|README)\.rst|src/mcookbook/.*\.py)$
        exclude: src/mcookbook/version.py
        additional_dependencies: [black==21.12b0]
  # <---- Formatting -------------------------------------------------------------------------------------------------

  # ----- Security -------------------------------------------------------------------------------------------------->
  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.0"
    hooks:
      - id: bandit
        alias: bandit-salt
        name: Run bandit against the code base
        args: [--silent, -lll, --skip, B701]
        files: ^(?!tests/).*\.py$
        exclude: src/mcookbook/version.py
  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.0"
    hooks:
      - id: bandit
        alias: bandit-tests
        name: Run bandit against the test suite
        args: [--silent, -lll, --skip, B701]
        files: ^tests/.*
  # <---- Security ---------------------------------------------------------------------------------------------------

  # ----- Code Analysis --------------------------------------------------------------------------------------------->
  - repo: https://github.com/pycqa/flake8
    rev: '4.0.1'
    hooks:
      - id: flake8
        exclude: ^(src/mcookbook/version\.py|\.pre-commit-hooks/.*\.py)$
        additional_dependencies:
        - flake8-mypy-fork
        - flake8-docstrings
        - flake8-typing-imports

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.930
    hooks:
      - id: mypy
        name: Run mypy against source
        files: ^src/.*\.py$
        args: [--strict]
        additional_dependencies:
          - types-attrs
          - types-setuptools
          - types-cachetools
          - pydantic

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.930
    hooks:
      - id: mypy
        name: Run mypy against tests
        files: ^tests/.*\.py$
        args: []
        additional_dependencies:
          - types-attrs
          - types-setuptools
          - types-cachetools
          - pydantic
  # <---- Code Analysis ----------------------------------------------------------------------------------------------

  # ----- Static Requirements --------------------------------------------------------------------------------------->
  - repo: https://github.com/saltstack/pip-tools-compile-impersonate
    rev: "4.2"
    hooks:

      # ----- Packaging Requirements -------------------------------------------------------------------------------->
      - id: pip-tools-compile
        alias: compile-py3.9-requirements
        name: Static Py3.9 Requirements
        files: ^requirements/base.txt$
        pass_filenames: false
        args:
          - -v
          - --py-version=3.9
          - --platform=linux
          - --include=requirements/base.txt
          - requirements/static/pkg/base.in

      - id: pip-tools-compile
        alias: compile-py3.10-requirements
        name: Static Py3.10 Requirements
        files: ^requirements/base.txt$
        pass_filenames: false
        args:
          - -v
          - --py-version=3.10
          - --platform=linux
          - --include=requirements/base.txt
          - requirements/static/pkg/base.in
      # <---- Packaging Requirements ---------------------------------------------------------------------------------

      # ----- CI Requirements---------------------------------------------------------------------------------------->
      - id: pip-tools-compile
        alias: compile-py3.9-ci-requirements
        name: Static CI Py3.9 Requirements
        files: ^requirements/((base|tests)\.txt|static/((pkg|ci)/(base|tests)\.in|pkg/py3\.9/base\.txt))$
        pass_filenames: false
        args:
          - -v
          - --py-version=3.9
          - --platform=linux
          - --include=requirements/static/pkg/py{py_version}/base.txt
          - --include=requirements/tests.txt
          - requirements/static/ci/tests.in

      - id: pip-tools-compile
        alias: compile-py3.10-ci-requirements
        name: Static CI Py3.10 Requirements
        files: ^requirements/((base|tests)\.txt|static/((pkg|ci)/(base|tests)\.in|pkg/py3\.10/base\.txt))$
        pass_filenames: false
        args:
          - -v
          - --py-version=3.10
          - --platform=linux
          - --include=requirements/static/pkg/py{py_version}/base.txt
          - --include=requirements/tests.txt
          - requirements/static/ci/tests.in
      # <---- CI Requirements ----------------------------------------------------------------------------------------

  # <---- Static Requirements ----------------------------------------------------------------------------------------
